all:
  children:
    k3s_master:
      hosts:
        vm-1
    prometheus:
      hosts:
        vm-1
    grafana:
      hosts:
        vm-1
    localhost:
      hosts:
        localhost
    agents:
      hosts:
        vm-2
